name: Documenter
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # NOTE: Python is necessary for the pre-rendering (minification) step
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install binary dependencies
        run: sudo apt-get update && sudo apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'
      - uses: julia-actions/cache@v2
      # - name: Install dependencies
      #   run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: >
          cd docs;
          DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
          julia --color=yes make.jl
      # - name: Upload site as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Docs build
      #     path: ./docs/build